#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/../.."
shopt -s extglob

script/bundle-linux --flatpak
archive_match="zorca(-[a-zA-Z0-9]+)?-linux-$(uname -m)\.tar\.gz"
archive=$(ls "target/release" | grep -E ${archive_match})
channel=$(<crates/zed/RELEASE_CHANNEL)

export CHANNEL="$channel"
export ARCHIVE="$archive"
if [[ "$channel" == "dev" ]]; then
    export APP_ID="dev.zorca.ZOrcaDev"
    export APP_NAME="ZOrca Dev"
    export BRANDING_LIGHT="#304CFF"
    export BRANDING_DARK="#071833"
    export ICON_FILE="app-icon-dev"
elif [[ "$channel" == "nightly" ]]; then
    export APP_ID="dev.zorca.ZOrcaNightly"
    export APP_NAME="ZOrca Nightly"
    export BRANDING_LIGHT="#713CFF"
    export BRANDING_DARK="#071833"
    export ICON_FILE="app-icon-nightly"
elif [[ "$channel" == "preview" ]]; then
    export APP_ID="dev.zorca.ZOrcaPreview"
    export APP_NAME="ZOrca Preview"
    export BRANDING_LIGHT="#FF654B"
    export BRANDING_DARK="#071833"
    export ICON_FILE="app-icon-preview"
elif [[ "$channel" == "stable" ]]; then
    export APP_ID="dev.zorca.ZOrca"
    export APP_NAME="ZOrca"
    export BRANDING_LIGHT="#304CFF"
    export BRANDING_DARK="#071833"
    export ICON_FILE="app-icon"
else
    echo "Invalid channel: '$channel'"
    exit
fi

envsubst < "crates/zed/resources/flatpak/manifest-template.json" > "$APP_ID.json"
flatpak-builder --user --install --force-clean build "$APP_ID.json"
flatpak build-bundle ~/.local/share/flatpak/repo "target/release/$APP_ID.flatpak" "$APP_ID"
echo "Created 'target/release/$APP_ID.flatpak'"
