#!/usr/bin/env bash

set -e

if ! command -v pandoc &> /dev/null
then
    brew install pandoc   # Install pandoc using Homebrew
fi

pandoc ./LICENSE-GPL -f markdown -t rtf -o ./script/terms/terms.rtf --standalone
