#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs ZOrca into ~/.local, making it available as ~/.local/bin/zorca.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export ZORCA_CHANNEL=$(<crates/zed/RELEASE_CHANNEL)
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="zorca-linux-${arch}.tar.gz"
export ZORCA_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
